### ISSUE TITLE
Recommend Blooprint's own 3rd party ADB camera app

### ISSUE THREAD

**Issue by ghost** [blooprint/blooprint-api#3]
For precision when it comes to pixel translation, we need minimal zoom(focus) differentiation between every input image after an arbitrary calibration call.  The only thing that should be changing from image to image should be the marker on the whiteboard.  Consider it a strobe, or claymation type deal.

Task - autofocus once during calibration, then use the same focus settings for every proceeding capture
- requires android development -> ADB

initiated repository ->[https://github.com/ddaaggeett/blooprint-camera]( https://github.com/ddaaggeett/blooprint-camera)

**Comment by ddaaggeett** [comment]
Considering the purpose of this API is to take the input image no matter the corner locations of the lit projection area and calibrate accordingly, **this issue is a mute point**. Either a [separate camera application](https://github.com/blooprint/blooprint-camera) should be written to eliminate auto-focus _interruption_ between camera captures, or this API could run its `calibration()` event each time the `stretch()` algorithm is run, thus allowing autofocus per default camera applications to be tolerated.

This would, of course, require (simple solution):
- dark corners to be a fixture on the whiteboard (adjustable magnets, perhaps) instead of our initial method of drawing the corners once for the single `calibration()` event.  These corners would be located every time an input image is dealt with
- updated corner search method: [Blooprint.setCorners()](https://github.com/blooprint/blooprint-api/blob/master/Blooprint.java) swipes each corner [outside -> in] since the user marks the corners within the lit area out to the bound lit projector area. The new dark fixture marks would be located outside the lit area, thus requiring the corner search method to swipe [inside -> out].
